version: '3'
services:
  webapp:
    build: ./flask-app
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: redis
    ports:
      - "6379:6379"
  nginx:
    build: ./nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - webapp
